name: 'Upstream Sync'

on:
  push:
    branches:
      - '**'
  schedule:
    - cron: '0 0 * * *'  # 8点运行 1 + 8

  workflow_dispatch:  # click the button on Github repo!

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    name: Sync latest commits from upstream repo

    steps:
    - name: Checkout target repo
      uses: actions/checkout@v3
      with:
        ref:  main
        persist-credentials: false

    - name: Sync upstream changes
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
      with:
        target_sync_branch: main
        target_repo_token: ${{ secrets.ACCESS_TOKEN }}
        upstream_sync_branch: main
        upstream_sync_repo: psf/black

        test_mode: false
      
    - name: New commits found
      if: steps.sync.outputs.has_new_commits == 'true'
      run: echo "New commits were found to sync."
    
    - name: No new commits
      if: steps.sync.outputs.has_new_commits == 'false'
      run: echo "There were no new commits."
      
    - name: Show value of 'has_new_commits'
      run: echo ${{ steps.sync.outputs.has_new_commits }}


# name: Sync From Raw Repo
# on:
#   push:
#     branches:
#       - '**'
#   schedule:
#     - cron: '0 1 * * *'  # 9点运行 1 + 8

# env:
#   REPO_SSH: git@github.com:SWHL/black.git
#   CLONE_URL: ${{ github.event.repository.clone_url }}
#   USER_NAME: SWHL
#   USER_EMAIL: liekkaskono@163.com
#   SUBMMIT_BRANCH: main

# jobs:
#   repo-sync:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Set SSH Environment
#         env:
#           DEPLOY_KEYS: ${{ secrets.DEPLOY_KEYS }}
#         run: |
#           mkdir -p ~/.ssh/
#           echo "$DEPLOY_KEYS" > ~/.ssh/id_rsa
#           chmod 600 ~/.ssh/id_rsa
#           chmod 700 ~/.ssh && chmod 600 ~/.ssh/*
#           git config --global user.name $USER_NAME
#           git config --global user.email $USER_EMAIL

#       - name: Sync from raw repo
#         run: |
#           git clone $REPO_SSH
#           cd black
#           git config pull.rebase true
#           git remote add upstream git@github.com:psf/black.git
#           git fetch upstream main
#           git checkout -b local_upstream upstream/main
#           git pull upstream main
#           git status
#           git rebase -q main
#           git checkout main

#           git merge local_upstream
#           git status
#           git push
#         #   git commit -m 'Actions auto update' || echo "nothing to commit"
#         #   git push -f origin ${SUBMMIT_BRANCH}
